---
management_enrollment_users: []
management_enrollment_create_home: true
management_enrollment_default_shell: /bin/bash
management_enrollment_managed_group: sudo
management_enrollment_remove_missing_sudoers: false
management_enrollment_skip_key_install_in_check_mode: true
